server:
  port: 8460

spring:
  application:
    name: producer
  profiles:
    active: local
  kafka:
    consumer:
      bootstrap-servers: 54.180.89.155:9290
      group-id: foo
      auto-offset-reset: earliest # latest, earliest, none
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
