spring:
  application:
    name: consume-domain
  config:
    use-legacy-processing: true
  datasource:
    consume-domain:
      read:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/kafka-study?autoReconnect=true&useSSL=false
        username: root
        password: a90a1027a
        readOnly: true
        connection-timeout: 20000
        max-lifetime: 110000
        maximumPoolSize: 20
        poolName: read
      write:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/kafka-study?autoReconnect=true&useSSL=false
        username: root
        password: a90a1027a
        readOnly: true
        connection-timeout: 20000
        max-lifetime: 110000
        maximumPoolSize: 20
        poolName: write
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      physical_naming_strategy: com.jd.infrastructure.CustomPhysicalNamingStrategy
      default_batch_fetch_size: 1000
      query:
        fail_on_pagination_over_collection_fetch: true
      use_sql_comments: true
      format_sql: true
      show_sql: true
      dialect: org.hibernate.dialect.MySQL55Dialect
      hbm2ddl:
        auto: none
