server:
  port: 8460

spring:
  application:
    name: producer
  profiles:
    active: local
  kafka:
    bootstrap-servers: 54.180.89.155:9290
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
